name: Update database and deploy to Cloud Run

on:
    workflow_dispatch:
    push:
      paths:
        - 'data/**'  
  
jobs:
    run-scraping-script:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Read .python-version
          run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ env.PYTHON_VERSION }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run build_database.py
          run: python src/chilean_humor/build_database.py
        - name: Set up Cloud Run
          uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            version: '275.0.0'
            service_account_email: ${{ secrets.GCP_SA_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
        - name: Deploy to Cloud Run
          run: |-
            gcloud components install beta
            gcloud config set run/region us-central1
            gcloud config set project Chilean-Humor
            datasette publish cloudrun humor.db --service chilean-humor -m metadata.json